openapi: 3.0.0

info:
  title: Cloud IQ
  description: |
    # Overview

    Cloud IQ is a comprehensive service that helps users & businesses optimize their cloud resources and reduce costs.
    It is a powerful tool that automates resource management and continuously monitors cloud infrastructure to identify areas of inefficiency and potential cost savings.

    One of the key features of Cloud-iq is its ability to identify and eliminate underutilized resources.
    For example, it can detect and shut down idle virtual machines, reducing unnecessary costs. It can also identify over-provisioned resources and suggest changes to optimize usage.

    Cloud IQ can also help businesses improve their overall cloud security by identifying potential security risks and vulnerabilities.

    Overall, Cloud-iq is a powerful service that can help businesses optimize their cloud resources, reduce costs, and improve security.
    By automating resource management, it allows businesses to make data-driven decisions about their cloud infrastructure and optimize their usage to achieve the best results.

    Currently, only AWS CloudWatch Log Group optimization is supported with more operations coming in the future.

    ## Experimental / In Development

    It is recommended that the AWS Role given to this software contain minimal permission.
    This package is subject to breaking changes at anytime.

    Currently the only permissions used are:
    - logs:PutRetentionPolicy
    - logs:DescribeLogGroups

    ## How to Use

    1. Generate AWS Credentials: accessKeyID, secretAccessKey, sessionToken are needed.
    1. Provide the credentials, region, and request specific parameters in the request body.
    1. Read operation documentation to learn more about it
    1. Invoke the operation through a HTTP Request
    1. Enjoy!

    ## Supported Services
    - CloudWatch Log Groups
      - Retention Policy

    ## Calling Rest Endpoint

    Requests can be made to either of these endpoints.

    - [https://cloud-iq-api.pateljay.io](https://cloud-iq-api.pateljay.io)

    ## Running Locally

    Repo Link: [https://github.com/jay-babu/cloud-iq](https://github.com/jay-babu/cloud-iq)

    - `./cloud-iq` if downloaded release file
    - `make run` if running from source
    - `make watch` tracks for file changes using `air`
  version: 0.0.0

servers:
  - url: https://cloud-iq-api.pateljay.io
  - url: http://localhost:8080

components:
  schemas:
    AwsLogRetentionInput:
      type: object
      properties:
        retentionInDays:
          type: integer
          format: int32
          default: 180
        accessKeyID:
          type: string
        secretAccessKey:
          type: string
        sessionToken:
          type: string
        region:
          type: string
      required: [accessKeyID, secretAccessKey, sessionToken, region]
    AwsLogRetentionOutput:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
      required: [messages]
    Message:
      type: object
      properties:
        message:
          type: string
        arn:
          type: string
        previousValue:
          type: integer
          format: int32
        newValue:
          type: integer
          format: int32
      required: [message, arn, previousValue, newValue]
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

paths:
  /aws/log_group/retention:
    post:
      description: |
        Modifies Log Group Retention in CloudWatch.
        Changes retention policy in CloudWatch Log Groups to be no greater than `retentionInDays` parameter.
        Log Groups with a smaller expiration date are not modified.
      operationId: logGroupRetention
      requestBody:
        description: Modify Log Group in CloudWatch
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AwsLogRetentionInput"
      responses:
        "200":
          description: Log Group Retention Saved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AwsLogRetentionOutput"
        "400":
          description: Bad Request.
        "5XX":
          description: Unexpected error.
