openapi: 3.0.0

info:
  title: Cloud Cleaner
  description: cloud-cleaner's job is very simple. It is to clean and optimize cloud resources.
  version: 0.0.5

servers:

  - url: http://localhost:32208/

components:

  schemas:
    AwsLogRetentionInput:
      type: object
      properties:
        retentionInDays:
          type: integer
          format: int32
          default: 180
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message


paths:
  /aws/log_group/retention:
    post:
      description: Modifies Log Group Retention in CloudWatch
      operationId: logGroupRetention
      requestBody:
        description: Modify Log Group in CloudWatch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AwsLogRetentionInput'
      responses:
        '204':
          description: Log Group Retention Saved.
        '400':
          description: Bad Request.
        '5XX':
          description: Unexpected error.

