openapi: 3.0.0

info:
  title: Auto Tune
  description: auto-tune's job is very simple. It is to clean and optimize cloud resources.
  version: 0.0.5

servers:

  - url: http://localhost:32208/

components:

  schemas:
    AwsLogRetentionInput:
      type: object
      properties:
        retentionInDays:
          type: integer
          format: int32
          default: 180
    AwsLogRetentionOutput:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      required: [messages]
    Message:
      type: object
      properties:
        message:
          type: string
        arn:
          type: string
        previousValue:
          type: integer
          format: int32
        newValue:
          type: integer
          format: int32
      required: [message, arn, previousValue, newValue]
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message


paths:
  /aws/log_group/retention:
    post:
      description: |
        Modifies Log Group Retention in CloudWatch.
        Changes retention policy in CloudWatch Log Groups to be no greater than `retentionInDays` parameter.
        Log Groups with a smaller expiration date are not modified.
      operationId: logGroupRetention
      requestBody:
        description: Modify Log Group in CloudWatch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AwsLogRetentionInput'
      responses:
        '200':
          description: Log Group Retention Saved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwsLogRetentionOutput'
        '400':
          description: Bad Request.
        '5XX':
          description: Unexpected error.

