name: release-type

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: go
          package-name: cloud-cleaner
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          prerelease: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          release-as: "0.0.0"

