name: release

on:
  push:
    # https://stackoverflow.com/a/61066906
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publishmatrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:

      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "cloud-cleaner"
        extra_files: LICENSE README.md
        # The default naming pattern uses the release name
        # Which makes difficult for scripts to download the correct version
        asset_name: cloud-cleaner-${{ matrix.goos }}-${{ matrix.goarch }}
        pre_command: export CGO_ENABLED=0
